---

- name: stunnel | stunnel.conf
  template:
    src: "stunnel.conf.j2"
    dest: "{{ stunnel_conf }}"
    owner: root
    group: root
    mode: 0644
  become: yes
  become_method: sudo
  notify: restart stunnel
